version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_order
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-order-data:/var/lib/mysql